name: 'Label Actions'
on: 
  pull_request:
    types: labeled

jobs:
  add-score:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'score')
    steps:
      - run: |
          echo ${{ github.event.label.name }},${{ github.event.pull_request.labels.*.name }}
          SCORE=${{ github.event.pull_request.labels.*.name }}
          USER=${{ github.event.head_commit.author.username }}
          echo ${{ github.event.head_commit.message }}
          echo $SCORE,$USER
          curl --data "user=$USER&score=$SCORE" --request POST https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/
