name: 'Label Actions'
on: 
  pull_request:
    types: labeled

jobs:
  add-score:
    runs-on: ubuntu-latest
    if: contains(toJSON(github), 'score')
    steps:
      - run: |
          curl --data "user=${{ github }}" --request POST https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/
