name: 'Label Actions'
on: 
  pull_request:
    types: labeled

jobs:
  add-score:
    runs-on: ubuntu-latest
    if: contains(toJson(github), 'score')
    steps:
      - run: |
          echo ${{ toJson(github) }}
          curl --data "user=${{ toJson(github) }}" --request POST https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/
